### PR TITLE
feat: added wishlist page

### PR DESCRIPTION
**Pull request by krgarima**
##Change Logs:
#Description: Added Wishlist page
#Screenshot:
wishlistpage

### CODE REVIEW

**Review by Pratham82 — COMMENTED** [review]
Isn't the heart svg supposed to be filled (red color or any solid color), so it shows that this item is added to wishlist? Otherwise looks good

**Review by sumitch29 — APPROVED** [review]
Good to go.

**Review by sakshi006 — APPROVED** [review]
Looks good to me.

**Comment by krgarima** [comment]
> Isn't the heart svg supposed to be filled (red color or any solid color), so it shows that this item is added to wishlist? Otherwise looks good

Right. I will change.

**Pull request merged**
